# Generated by Django 3.1.6 on 2021-03-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='descriptionImage',
            new_name='description',
        ),
    ]
