# Generated by Django 3.1.6 on 2021-03-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20210310_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='description',
            new_name='descriptionImage',
        ),
    ]
